---
title: "1-1-1_process_lymphocytes"
output: html_document
date: "2025-04-07"
---

```{r}
library(tidyverse)
library(Seurat)
library(scater)
```

```{r}
library(RColorBrewer)
getPalette.1 <- colorRampPalette(brewer.pal(n = 12,name = "Set3"))
pal <- c(brewer.pal(n = 12,name = "Set3"),brewer.pal(n = 12,name = "Paired"),brewer.pal(n = 8,name = "Accent"))
pal[2] <- "darkred"
pal[9] <- "grey25"
pal[23] <- "turquoise4"
pal[19] <- colors()[60]
pal[13] <- "darkblue"
pal[28] <- colors()[16]
pal[31] <- colors()[54] 
pal <- c(pal,colors()[c(85,84,83,89,45,31,41,42,26,29,10,139,107,108,120,109,119,121,143)])
```

```{r}
indir <- "RDS/"
outdir <- "RDS/"
if (!dir.exists(outdir)) dir.create(outdir)
```

```{r}
whole <- readRDS(paste0(outdir,"whole_V1p2.RDS"))
```

## isolate (pan)-lymphocytes


```{r}
lymphocytes <- subset(whole, subset = RNA_snn_res.0.2 %in% c(1,3,9))
```

```{r}
DimPlot(lymphocytes)
```

```{r}
lymphocytes <- FindVariableFeatures(object = lymphocytes, selection.method = 'mean.var.plot', mean.cutoff = c(0.0125, 5), dispersion.cutoff = c(0.5, Inf))
VariableFeatures(lymphocytes) <-  VariableFeatures(lymphocytes)[!grepl("^Tra|^Trb|^Igh|^Igk|Mamu-a", VariableFeatures(lymphocytes))]
VariableFeaturePlot(lymphocytes)
lymphocytes <- ScaleData(object = lymphocytes, features = VariableFeatures(object = lymphocytes), vars.to.regress = c("nCount_RNA", "percent.mt"))
lymphocytes <- RunPCA(object = lymphocytes,
                features =  VariableFeatures(object = lymphocytes),
                dims = 1:50)
gc()
ElbowPlot(lymphocytes,ndims = 50)
```


```{r}
lymphocytes <- RunHarmony(object = lymphocytes, group.by.vars = c("orig.ident"), max.iter.harmony = 20)
lymphocytes <- RunUMAP(lymphocytes,dims = 1:30,reduction = "harmony")
lymphocytes <- RunTSNE(lymphocytes,dims = 1:30,reduction = "harmony")

lymphocytes <- FindNeighbors(lymphocytes, dims = 1:30,reduction = "harmony")
for(res in seq(0.1, 1, 0.1))  {   
  lymphocytes <- FindClusters(object = lymphocytes, resolution = res, print.output = 0, save.SNN = TRUE)
} 
gc()
lymphocytes <- JoinLayers(lymphocytes)
```

```{r}
Idents(lymphocytes) <- "RNA_snn_res.0.2"
DimPlot(lymphocytes, group.by = "RNA_snn_res.0.2",label = T)+scale_color_manual(values = pal)
DimPlot(lymphocytes, group.by = "orig.ident",shuffle = T)+scale_color_manual(values = pal)
FeaturePlot(lymphocytes, features = "Adgre1",label = T)+scale_color_gradientn(colors = c("grey90","red2","red3"))

VlnPlot(lymphocytes,features = c("log10_nFeature_RNA"),alpha = 0.1) +scale_fill_manual(values = pal)
VlnPlot(lymphocytes,features = c("log10_nCount_RNA"),alpha = 0.1) +scale_fill_manual(values = pal)
VlnPlot(lymphocytes,features = c("percent.mt"),alpha = 0.1) +scale_fill_manual(values = pal)

DotPlot(lymphocytes,features = c("Ptprc","Cd3e","Cd8a","Cd4","Cd19","Ccr2","Adgre1","Lyz2","Klrb1c","Tyrobp","Ncam1","Xcr1","Ncr1","Siglech","Mpo","S100a8","Cd200r3","Fcer1a","Fcer2a","Flt3","Pecam1","Epcam","Krt1","Myct1","Hbb-bs","Pf4","Col1a1","Mki67"),group.by = "RNA_snn_res.0.2")+RotatedAxis()+scale_color_gradientn(colors = c("grey90","red2","red3"))

DimPlot(lymphocytes,group.by = "DF.classifications")+scale_color_manual(values = pal[c(19,21)])
DotPlot(lymphocytes,features = c("Ptprc","Cd3e","Cd8a","Cd8b1","Cd4","Ccr7","Tcf7","Lef1","Foxp3","Klrb1c","Tyrobp","Prf1","Gzma","Gzmk","Lag3","Cd44","Pdcd1","Tox","Eomes","Ikzf2","Mki67","H2-Ab1","Cd74"),group.by = "RNA_snn_res.0.2")+RotatedAxis()+scale_color_gradientn(colors = c("grey90","red2","red3"))
```

```{r}
FeatureScatter(lymphocytes, feature1 = "Adgre1",feature2 = "log10_nCount_RNA")
FeatureScatter(lymphocytes, feature1 = "Adgre1",feature2 = "log10_nFeature_RNA")
```

```{r}
VlnPlot(lymphocytes,features = "Adgre1", group.by = "RNA_snn_res.0.5",split.by = "orig.ident")
VlnPlot(lymphocytes,features = "Cd3e", group.by = "RNA_snn_res.0.5",split.by = "orig.ident")
```

```{r}
DotPlot(lymphocytes,features = c("Ptprc","Cd3e","Cd8a","Cd8b1","Cd4","Ccr7","Arg1","Mrc1","Nos2","Adgre1","Lyz2","Cx3cr1","Cxcr3","Lgals3","Lamp3","Trem2","Apo3","Gpnmb"),group.by = "RNA_snn_res.0.2")+RotatedAxis()+scale_color_gradientn(colors = c("grey90","red2","red3"))

```

```{r}
saveRDS(lymphocytes, file = paste0(outdir,"lymphocytes_V1p2.RDS"))
```

```{r}
myeloid_s <- subset(lymphocytes , subset= RNA_snn_res.0.2 %in% c(0) )
```

```{r}
saveRDS(myeloid_s, file = paste0(outdir,"myeloid-s_V1p2.RDS"))
```


## second iter with TAM-like cells removed

```{r}

lymphocytes <- subset(lymphocytes, subset = RNA_snn_res.0.2 %in% c(1:8))
```

```{r}
DimPlot(lymphocytes,group.by = "DF.classifications")+scale_color_manual(values = pal[c(19,21)])
```

```{r}
lymphocytes <- FindVariableFeatures(object = lymphocytes, selection.method = 'mean.var.plot', mean.cutoff = c(0.0125, 5), dispersion.cutoff = c(0.5, Inf))
VariableFeatures(lymphocytes) <-  VariableFeatures(lymphocytes)[!grepl("^Tra|^Trb|^Igh|^Igk|Mamu-a", VariableFeatures(lymphocytes))]
VariableFeaturePlot(lymphocytes)
lymphocytes <- ScaleData(object = lymphocytes, features = VariableFeatures(object = lymphocytes), vars.to.regress = c("nCount_RNA", "percent.mt"))
lymphocytes <- RunPCA(object = lymphocytes,
                features =  VariableFeatures(object = lymphocytes),
                dims = 1:50)
gc()
ElbowPlot(lymphocytes,ndims = 50)
```

```{r}
lymphocytes <- RunHarmony(object = lymphocytes, group.by.vars = c("orig.ident"), max.iter.harmony = 20)
lymphocytes <- RunUMAP(lymphocytes,dims = 1:20,reduction = "harmony")
lymphocytes <- RunTSNE(lymphocytes,dims = 1:20,reduction = "harmony")

lymphocytes <- FindNeighbors(lymphocytes, dims = 1:20,reduction = "harmony")
for(res in seq(0.1, 1, 0.1))  {   
  lymphocytes <- FindClusters(object = lymphocytes, resolution = res, print.output = 0, save.SNN = TRUE)
} 
gc()
lymphocytes <- JoinLayers(lymphocytes)
```

```{r}
Idents(lymphocytes) <- "RNA_snn_res.0.2"
DimPlot(lymphocytes, group.by = "RNA_snn_res.0.2",label = T)+scale_color_manual(values = pal)
DimPlot(lymphocytes, group.by = "orig.ident",shuffle = T)+scale_color_manual(values = pal)
FeaturePlot(lymphocytes, features = "Adgre1",label = T)+scale_color_gradientn(colors = c("grey90","red2","red3"))

VlnPlot(lymphocytes,features = c("log10_nFeature_RNA"),alpha = 0.1) +scale_fill_manual(values = pal)
VlnPlot(lymphocytes,features = c("log10_nCount_RNA"),alpha = 0.1) +scale_fill_manual(values = pal)
VlnPlot(lymphocytes,features = c("percent.mt"),alpha = 0.1) +scale_fill_manual(values = pal)

DotPlot(lymphocytes,features = c("Ptprc","Cd3e","Cd8a","Cd4","Cd19","Ccr2","Adgre1","Lyz2","Klrb1c","Tyrobp","Ncam1","Xcr1","Ncr1","Siglech","Mpo","S100a8","Cd200r3","Fcer1a","Fcer2a","Flt3","Pecam1","Epcam","Krt1","Myct1","Hbb-bs","Pf4","Col1a1","Mki67"),group.by = "RNA_snn_res.0.2")+RotatedAxis()+scale_color_gradientn(colors = c("grey90","red2","red3"))
DotPlot(lymphocytes,features = c("Ptprc","Cd3e","Cd8a","Cd8b1","Cd4","Ccr7","Arg1","Mrc1","Nos2","Adgre1","Lyz2","Cx3cr1","Cxcr3","Lgals3","Lamp3","Trem2","Apo3","Gpnmb"),group.by = "RNA_snn_res.0.2")+RotatedAxis()+scale_color_gradientn(colors = c("grey90","red2","red3"))
DotPlot(lymphocytes,features = c("Ptprc","Cd3e","Cd8a","Cd8b1","Cd4","Ccr7","Tcf7","Lef1","Foxp3","Klrb1c","Tyrobp","Prf1","Gzma","Gzmk","Lag3","Cd44","Pdcd1","Tox","Eomes","Ikzf2","Mki67","H2-Ab1","Cd74"),group.by = "RNA_snn_res.0.2")+RotatedAxis()+scale_color_gradientn(colors = c("grey90","red2","red3"))

DimPlot(lymphocytes,group.by = "DF.classifications")+scale_color_manual(values = pal[c(19,21)])
```

```{r}
FeatureScatter(lymphocytes,feature1 = "Adgre1",feature2 = "percent.mt")
```

```{r}
saveRDS(lymphocytes, file = paste0(outdir,"lymphocytes_V1p3.RDS"))
```

```{r}
lymphocytes <- readRDS(file = paste0(outdir,"lymphocytes_V1p3.RDS"))
```

## prelim annotation

```{r}
Idents(lymphocytes) <- "RNA_snn_res.0.2"
lym_res02_marker <- FindAllMarkers(lymphocytes)
```
```{r}
selected_markers <- lym_res02_marker %>% group_by(cluster) %>% filter(!grepl("^ENSM|^Gm|Rik$",gene)) %>% slice_max(order_by = avg_log2FC*pct.1 , n = 3, with_ties = F)

DotPlot(lymphocytes,features = selected_markers$gene,group.by = "RNA_snn_res.0.2")+RotatedAxis()+scale_color_gradientn(colors = c("grey90","red2","red3"))
```
```{r}
DimPlot(lymphocytes, group.by = "RNA_snn_res.0.7",label = T)+scale_color_manual(values = pal)
```


```{r}
DotPlot(lymphocytes,features = c("Ptprc","Cd19","Cd3e","Cd8a","Cd8b1","Cd4","Foxp3","Rorc","Gata3","Tbx21","Ccr7","Tcf7","Lef1","Klrb1c","Tyrobp","Prf1","Gzma","Gzmk","Lag3","Cd44","Pdcd1","Tox","Eomes","Ikzf2","Il1r1","Il7r","Mki67"),group.by = "RNA_snn_res.0.7")+RotatedAxis()+scale_color_gradientn(colors = c("grey90","red2","red3"))
```

```{r}
Idents(lymphocytes) <- "RNA_snn_res.0.7"
FeaturePlot(lymphocytes,features = c("Cd8a"),label = T)+scale_color_gradientn(colors = c("grey90","red2","red3"))
FeaturePlot(lymphocytes,features = c("Cd4"),label = T)+scale_color_gradientn(colors = c("grey90","red2","red3"))
```

```{r}
clust_prop_grouped <- lymphocytes@meta.data  %>%   
  group_by(RNA_snn_res.0.7,orig.ident) %>% 
  summarise(n = n()) %>% ungroup() %>% group_by(orig.ident) %>% mutate(cluster_prop = n/sum(n))


ratio <- clust_prop_grouped %>% group_by(RNA_snn_res.0.7) %>% reframe(FC = log2(cluster_prop[orig.ident == "KO_HC"]/cluster_prop[orig.ident == "WT_HC"]))

g4 <- ggplot(ratio, aes( x = reorder(RNA_snn_res.0.7, -FC), y = FC))+
  geom_bar(aes(fill = RNA_snn_res.0.7),stat = "identity", position = "dodge")+
  scale_fill_manual(values = pal)+theme_classic()+
  ylab("log2 proportion in KO v.s. WT")+
  xlab("res=0.7 clusters")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))
g4
```

```{r}
lymphocytes$compartment <- "Lymphocytes"
```

```{r}
lymphocytes@meta.data <- lymphocytes@meta.data %>% mutate(
  annotation_V1 = case_match(
    as.character(RNA_snn_res.0.7),
    "0" ~ "L0: NK",
    "1" ~ "L1: Stem-like CD8 Tex",
    "2" ~ "L2: NKT",
    "3" ~ "L3: Treg/Th2",
    "4" ~ "L4: Tem/ex",
    "5" ~ "L5: Tcm/em",
    "6" ~ "L6: Th2",
    "7" ~ "L7: B cells",
    "8" ~ "L8: Th",
    "9" ~ "L9: gdT",
    "10" ~ "L10: ILC3",
    "11" ~ "L11: proliferating cells"
  )
)

```

```{r}
DimPlot(lymphocytes, group.by = "annotation_V1",label = T,repel = T,label.box = T)+scale_color_manual(values = pal)+scale_fill_manual(values = pal)
```
```{r}
saveRDS(lymphocytes, file = paste0(outdir,"lymphocytes_V1p3.RDS"))
```

