---
title: "3-1_visualization_myeloid"
output: html_document
date: "2025-05-07"
---

```{r}
library(tidyverse)
library(Seurat)
library(scater)
library(mascarade)
library(data.table)
library(ComplexHeatmap)
library(circlize)
```

```{r}
library(RColorBrewer)
getPalette.1 <- colorRampPalette(brewer.pal(n = 12,name = "Set3"))
pal <- c(brewer.pal(n = 12,name = "Set3"),brewer.pal(n = 12,name = "Paired"),brewer.pal(n = 8,name = "Accent"))
pal[2] <- "darkred"
pal[9] <- "grey25"
pal[23] <- "darkblue"
pal[19] <- colors()[60]
pal[13] <- "turquoise4"
pal[28] <- colors()[16]
pal[31] <- colors()[54] 
pal <- c(pal,colors()[c(85,84,83,89,45,31,41,42,26,29,10,139,107,108,120,109,119,121,143)])
```

Note: since proportion information relies on whole dataset, proportion plots will be made here. An easier way is to export the metadata for visualization and manipulation

```{r}
indir <- "RDS/"
outdir <- "formal-visualization/"
if (!dir.exists(outdir)) dir.create(outdir)
```

```{r}
whole <- readRDS(file = paste0(indir,"whole_V1p6.RDS"))
myeloid <- readRDS(file = paste0(indir,"myeloid_V1p5.RDS"))
```

## overview plots

```{r}
whole@meta.data <- whole@meta.data %>%
  mutate(highlight = case_match(
    compartment,
    "Myeloid" ~ "Myeloid",
    .default = "NA"
  ))
```

```{r}
DimPlot(whole,group.by = "highlight") + 
  scale_color_manual(values = c("Myeloid" = colorRampPalette(brewer.pal(11, "BrBG"))(8)[3],na.value = "grey90"))
g <- DimPlot(whole,group.by = "highlight") + 
  scale_color_manual(values = c("Myeloid" = colorRampPalette(brewer.pal(11, "BrBG"))(8)[3],na.value = "grey90"))
ggsave(filename = paste0(outdir,"Supp_Whole_Myeloid_unsplit.pdf"), plot = g, units = "cm",height = 10,width = 10)
```


```{r}
maskTable <- generateMask(dims=myeloid@reductions$umap@cell.embeddings, 
                          clusters=myeloid$annotation_V1)
data <- data.table(myeloid@reductions$umap@cell.embeddings, 
                   cluster=myeloid$annotation_V1,
                   myeloid@meta.data)
centers <- data %>% 
  dplyr::group_by(cluster) %>% 
  dplyr::summarize(umap_1 = median(umap_1), umap_2 = median(umap_2)) 


data$orig.ident <- factor(data$orig.ident, levels = c("WT_HC","KO_HC"))
```

```{r}
g <- ggplot(data, aes(x=umap_1, y=umap_2)) + 
    geom_point(aes(color=cluster), size = 0.5) + 
    geom_path(data=maskTable, aes(group=group)) +
  geom_text(data = centers, aes(label=cluster), size = 3.5, color = "black") +
    scale_color_manual(values = pal)+
    coord_fixed() + 
    theme_classic()+facet_wrap(~orig.ident)+theme(legend.position = "bottom")+
  guides(color = guide_legend(override.aes = list(size = 3))) 
g
ggsave(filename = paste0(outdir,"myeloid_V1p5_annotated_umap_split_mascarade.pdf"), plot = g, width = 18, height = 7)

g <- ggplot(data, aes(x=umap_1, y=umap_2)) + 
    geom_point(aes(color=cluster), size = 0.5) + 
    geom_path(data=maskTable, aes(group=cluster)) +
  ggrepel::geom_text_repel(data = centers, aes(label=cluster), size = 5, color = "black",min.segment.length = unit(0, 'lines'),force = 5, label.padding = 5,max.overlaps = Inf,direction = "both") +
    scale_color_manual(values = pal[c(1:8,10:15)])+
    coord_fixed() + 
    theme_classic()+theme(legend.position = "bottom")+
  guides(color = guide_legend(override.aes = list(size = 3))) 
g
ggsave(filename = paste0(outdir,"myeloid_V1p5_annotated_umap_mascarade.pdf"), plot = g, width = 18, height = 7)
```

## mo-mac plots

```{r}
p1 <- DotPlot(myeloid, group.by = "annotation_V1",features = c("Ccr2","Adgre1","S100a8","Flt3","Xcr1","Clec10a","Sirpa","Clec9a","Ccr7","Cd200r3","Tpsb2","Mki67"))+scale_color_gradientn(colors = c("grey90","red2","red3"))+ RotatedAxis()
ggsave(filename = paste0(outdir,"Supp_Myeloid_Dotplot_annotation.pdf"), plot = p1, units = "cm",height = 24,width = 20)
```


```{r}
gene_of_interests <- t(as.matrix(myeloid[["RNA"]]$data[c("Nos2","Cx3cr1"),]))
```

```{r}
data <- cbind(data, gene_of_interests)
```

```{r}
data <- data %>% mutate(
  Nos2_Cx3cr1_co = Nos2-Cx3cr1
)
```

```{r}
g <- ggplot(data, aes(x=umap_1, y=umap_2)) + 
    geom_point(aes(color = Nos2_Cx3cr1_co),size = 2) + 
    scale_color_gradientn(colors = c("darkblue","grey90","red3"))+
    geom_path(data=maskTable, aes(group=group)) +
  geom_text(data = centers, aes(label=cluster), size = 3.5, color = "black") +
    coord_fixed() + 
    theme_classic()+facet_wrap(~orig.ident) 
g
ggsave(filename = paste0(outdir,"myeloid_V1p5_nos2-cx3cr1_mascarade.pdf"), plot = g, width = 18, height = 7)
```

```{r}
g <- ggplot(data, aes(x=umap_1, y=umap_2)) + 
    geom_point(aes(fill = Nos2), shape=21,size = 1,alpha = 0.4) + 
    scale_fill_gradientn(colors = c("grey95","red2","red3"))+
    geom_point(aes(color = Cx3cr1),shape=21,size = 1, alpha = 1)+
  scale_color_gradientn(colors = c("grey95","lightblue","darkblue"))+
    geom_path(data=maskTable, aes(group=group)) +
  geom_text(data = centers, aes(label=cluster), size = 3.5, color = "black") +
    coord_fixed() + 
    theme_classic()+facet_wrap(~orig.ident) 
g
#ggsave(filename = paste0(outdir,"myeloid_V1p5_nos2-cx3cr1_mascarade.pdf"), plot = g, width = 18, height = 7)
```

```{r}
table(whole$cell_type)
```

```{r}
mono_mac <- subset(whole,subset = cell_type == "mo-Mac")
```

```{r}
avg_mono_mac <- AggregateExpression(mono_mac, assays = "RNA",features = c("Adgre1", "Cd14", "Ccr2", "Mertk","Tnf", "Fpr2", "Isg15", "Nos2", "Rsad2", "Spp1", "Il7r", "Ifitm3", "Ifit1", "Ifit3", "Il1b", "Slc2a1","Tgfb", "Cd274", "Arg1","Cd226", "Chil3", "Cx3cr1", "Mrc1","Trem2", "C1qa","Ccl2","Mki67"), return.seurat = T,group.by = c("annotation_V1","orig.ident"))

```

```{r}
celltype_pal_mono <- pal[c(1,2,5)]
avg_mono_mac$sample <- rep(c("WT_HC","KO_HC"),6)
names(celltype_pal_mono) <- unique(unname(avg_mono_mac$annotation_V1))
col = list(
  Cell_type = celltype_pal_mono,
  Sample = c("WT_HC"="red3", "KO_HC" = "darkblue")
)
ha <- HeatmapAnnotation(
   Cell_type = unname(avg_mono_mac$annotation_V1), Sample = unname(avg_mono_mac$sample),
  col = col
)
mat <-  GetAssayData(avg_mono_mac,layer = "scale.data")
Heatmap(mat,name = "Mono/Mac",top_annotation = ha,cluster_rows = T,cluster_columns = F,show_row_names = TRUE,show_column_names = F,row_names_side = "left",col = colorRamp2(c(-2,0,2),c("darkblue","white","red")))
```


```{r}
pdf(paste0(outdir,"mono_mac_marker_Heatmap.pdf"))
Heatmap(mat,name = "mono_mac dataset",top_annotation = ha,cluster_rows = T,cluster_columns = F,show_row_names = TRUE,show_column_names = F,row_names_side = "left",col = colorRamp2(c(-2,0,2),c("darkblue","white","red")))
dev.off()
```

```{r}
g <- VlnPlot(mono_mac,features = c("Cx3cr1", "Nos2"),alpha = 0,group.by = "annotation_V1",split.by = "orig.ident",fill.by = "ident")
ggsave(filename = paste0(outdir,"Vln_Mac_Cx3cr1_Nos2_split.pdf"), plot = g, units = "cm",height = 12,width = 24)
```

```{r}
VlnPlot(mono_mac,features = "Cx3cr1",group.by = "annotation_V1", split.by = "orig.ident",fill.by = "ident")+scale_fill_manual(values = c("KO_HC"="darkblue","WT_HC" = "red2"))
VlnPlot(mono_mac,features = "Nos2",group.by = "annotation_V1", split.by = "orig.ident",fill.by = "ident")+scale_fill_manual(values = c("KO_HC"="darkblue","WT_HC" = "red2"))
```
### mo-mac characterization

```{r}
Idents(mono_mac) <- "annotation_V1"
mo_mac_markers <- FindAllMarkers(mono_mac)
```
```{r}
markers <- mo_mac_markers %>% filter(p_val_adj < 0.01) %>% group_by(cluster) %>% slice_max(order_by = abs(avg_log2FC) , n = 20, with_ties = F)
```

### marker heatmap

```{r}
avg_mono_mac <- AggregateExpression(mono_mac, assays = "RNA",features = markers$gene, return.seurat = T,group.by = c("annotation_V1","orig.ident"))

```

```{r}
celltype_pal_mono <- pal[c(1,2,5)]
avg_mono_mac$sample <- rep(c("WT_HC","KO_HC"),6)
names(celltype_pal_mono) <- unique(unname(avg_mono_mac$annotation_V1))
col = list(
  Cell_type = celltype_pal_mono,
  Sample = c("WT_HC"="red3", "KO_HC" = "darkblue")
)
ha <- HeatmapAnnotation(
   Cell_type = unname(avg_mono_mac$annotation_V1), Sample = unname(avg_mono_mac$sample),
  col = col
)
mat <-  GetAssayData(avg_mono_mac,layer = "scale.data")
Heatmap(mat,name = "Mono/Mac",top_annotation = ha,cluster_rows = T,cluster_columns = F,show_row_names = TRUE,show_column_names = F,row_names_side = "left",col = colorRamp2(c(-2,0,2),c("darkblue","white","red")))
```

```{r}
pdf(paste0(outdir,"mono_mac_marker-unsurpervised_Heatmap.pdf"),height = 10, width = 6)
Heatmap(mat,name = "mono_mac dataset",top_annotation = ha,cluster_rows = T,cluster_columns = F,show_row_names = TRUE,show_column_names = F,row_names_side = "left",col = colorRamp2(c(-2,0,2),c("darkblue","white","red")))
dev.off()
```


