---
title: "Aux_1-1_check_Doub-like_clusters"
output: html_document
date: "2025-04-16"
---

```{r}
library(Seurat)
library(tidyverse)
```



```{r}
library(RColorBrewer)
getPalette.1 <- colorRampPalette(brewer.pal(n = 12,name = "Set3"))
pal <- c(brewer.pal(n = 12,name = "Set3"),brewer.pal(n = 12,name = "Paired"),brewer.pal(n = 8,name = "Accent"))
pal[2] <- "darkred"
pal[9] <- "grey25"
pal[23] <- "turquoise4"
pal[19] <- colors()[60]
pal[13] <- "darkblue"
pal[28] <- colors()[16]
pal[31] <- colors()[54] 
pal <- c(pal,colors()[c(85,84,83,89,45,31,41,42,26,29,10,139,107,108,120,109,119,121,143)])
```

Use V1.2 whole

```{r}
indir <- "RDS/"
outdir <- "RDS/"
if (!dir.exists(outdir)) dir.create(outdir)
```

```{r}
whole <- readRDS(paste0(outdir,"whole_V1p2.RDS"))
```


```{r}
DotPlot(whole,features = c("Ptprc","Cd3e","Cd8a","Cd8b1","Cd4","Ccr7","Arg1","Mrc1","Nos2","Adgre1","Lyz2","Cx3cr1","Cxcr3","Lgals3","Lamp3","Trem2","Apoe","Gpnmb"),group.by = "RNA_snn_res.0.6")+RotatedAxis()+scale_color_gradientn(colors = c("grey90","red2","red3"))

DotPlot(whole,features = c("Pdcd1","Havcr2","Tox","Ctla4","Cd3e","Cd8a","Cd8b1","Cd4","Foxp3","Rorc","Gata3","Tbx21","Ccr7","Tcf7","Lef1","Slamf6","Fos","Prdm1","Xcl1","Il7r","Klrb1c","Klra3","Klrd1","Zeb2","Prf1","Isg15","Cx3cr1","Gzma","Gzmk","Lag3","Cd44","Eomes","Ikzf2","Il1r1","Entpd1","Mki67"),group.by = "RNA_snn_res.0.6",cluster.idents = T)+RotatedAxis()+scale_color_gradientn(colors = c("grey90","red2","red3"))
```
```{r}
FeatureScatter(whole, feature1 = "Cd3e", feature2 = "Adgre1", group.by = "RNA_snn_res.0.6")+scale_color_manual(values = pal)
FeatureScatter(whole, feature1 = "Cd3d", feature2 = "Adgre1", group.by = "RNA_snn_res.0.6")+scale_color_manual(values = pal)
FeatureScatter(whole, feature1 = "Cd8a", feature2 = "Adgre1", group.by = "RNA_snn_res.0.6")+scale_color_manual(values = pal)
FeatureScatter(whole, feature1 = "Cd4", feature2 = "Adgre1", group.by = "RNA_snn_res.0.6")+scale_color_manual(values = pal)
FeatureScatter(whole, feature1 = "Gzma", feature2 = "Adgre1", group.by = "RNA_snn_res.0.6")+scale_color_manual(values = pal)
FeatureScatter(whole, feature1 = "Tox", feature2 = "Adgre1", group.by = "RNA_snn_res.0.6")+scale_color_manual(values = pal)
```

